#!/usr/bin/env node
// Bundles everything in data/ into site/data.js so the site works as plain
// static files (no server or fetch needed: opening site/index.html works too).
//
//   node scripts/build.mjs
//
// data/charts/YYYY-MM.json  one file per month (Apple Music Replay or Last.fm)
// data/replay/YYYY.json     Apple's own full-year Replay lists
// data/images.json          [type, title, artist, imageUrl] rows
// data/aliases.json         renames (e.g. an artist Apple renamed) so histories join up
// data/tracks.json          which charted songs belong to which charted album
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = p => JSON.parse(readFileSync(join(ROOT, p), 'utf8'));
const problems = [];

const months = readdirSync(join(ROOT, 'data/charts'))
  .filter(f => /^\d{4}-\d{2}\.json$/.test(f)).sort()
  .map(f => {
    const m = read('data/charts/' + f);
    if (m.month !== f.slice(0, 7)) problems.push(`${f}: "month" says ${m.month}`);
    for (const cat of ['artists', 'songs', 'albums']) {
      const rows = m[cat] || [];
      if (!rows.length) problems.push(`${f}: no ${cat}`);
      const w = cat === 'artists' ? 2 : 3;
      rows.forEach((r, i) => {
        if (r.length !== w || typeof r[w - 1] !== 'number') problems.push(`${f}: ${cat} #${i + 1} malformed`);
        else if (i && r[w - 1] > rows[i - 1][w - 1]) problems.push(`${f}: ${cat} #${i + 1} has more than #${i}`);
      });
    }
    return m;
  });

const replay = {};
if (existsSync(join(ROOT, 'data/replay'))) {
  for (const f of readdirSync(join(ROOT, 'data/replay')).filter(f => /^\d{4}\.json$/.test(f))) {
    const r = read('data/replay/' + f);
    replay[f.slice(0, 4)] = { artists: r.artists || [], songs: r.songs || [], albums: r.albums || [] };
  }
}
const images = existsSync(join(ROOT, 'data/images.json')) ? read('data/images.json') : [];
const aliases = existsSync(join(ROOT, 'data/aliases.json')) ? read('data/aliases.json') : {};
const tracks = existsSync(join(ROOT, 'data/tracks.json')) ? read('data/tracks.json') : {};
delete tracks._comment;
delete aliases._comment;

const out = { builtAt: new Date().toISOString().slice(0, 10), months, replay, images, aliases, tracks };
writeFileSync(join(ROOT, 'site/data.js'),
  '// Generated by scripts/build.mjs from data/. Do not edit by hand.\nwindow.MUSICBOX = ' + JSON.stringify(out) + ';\n');

problems.forEach(p => console.warn('warning:', p));
console.log(`site/data.js: ${months.length} months (${months[0]?.month} to ${months.at(-1)?.month}), ` +
  `${Object.keys(replay).length} Replay years, ${images.length} images`);
