#!/usr/bin/env node
// Bundles each data folder into a data.js so the site works as plain static files
// (no server or fetch needed: opening site/index.html works too).
//
//   node scripts/build.mjs          builds every site
//
// data/                → site/data.js           (the main site, at the root)
// profiles/<name>/     → site/<name>/data.js     (another person's site, at /<name>/)
//                        plus site/<name>/index.html, generated from site/index.html so
//                        it stays the exact same site (it shares styles.css, charts.js, app.js)
// profiles/<name>/ with a weeks/ folder (YYYY-MM-DD.json, from import-spotify.mjs --weeks)
//                      → site/<name>/m/ (monthly charts), site/<name>/w/ (weekly charts)
//                        and site/<name>/index.html, a small page to pick one
//
// Inside a data folder (all optional except the month lists):
// charts/YYYY-MM.json       one file per month (Apple Music Replay or Last.fm)
// spotify/YYYY-MM.json      Spotify months (scripts/import-spotify.mjs); merged with any other source
// deezer/YYYY-MM.json       Deezer months (scripts/import-deezer.mjs); same
// replay/YYYY.json          Apple's own full-year Replay lists
// images.json               [type, title, artist, imageUrl] rows
// aliases.json              renames (e.g. an artist Apple renamed) so histories join up
// credits.json              verified guest credits missing from imports
// tracks.json               which charted songs belong to which charted album
// lengths.json              song lengths in seconds, for album minutes worked out from songs
// releases.json             album groups and excluded single releases
// collection-listening.json recovered collection minutes from raw history
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

function buildSite(dataDir, outDir, { weekly = false, views = null } = {}) {
  const at = p => join(ROOT, dataDir, p);
  const read = p => JSON.parse(readFileSync(at(p), 'utf8'));
  const opt = (p, empty) => existsSync(at(p)) ? read(p) : empty;
  const problems = [];

  // Month lists can come from several folders; a month present in more than one is merged
  // (numbers added up) by site/charts.js, e.g. Apple Music + Spotify in the same month.
  const lists = (dirs, re, field) => dirs.filter(d => existsSync(at(d))).flatMap(d => readdirSync(at(d))
    .filter(f => re.test(f)).sort().map(f => d + '/' + f))
    .map(path => {
      const f = path.split('/').pop();
      const m = read(path);
      if (m[field] !== f.slice(0, -5)) problems.push(`${f}: "${field}" says ${m[field]}`);
      for (const cat of ['artists', 'songs', 'albums']) {
        const rows = m[cat] || [];
        if (!rows.length) problems.push(`${f}: no ${cat}`);
        const w = cat === 'artists' ? 2 : 3;
        rows.forEach((r, i) => {
          if (r.length !== w || typeof r[w - 1] !== 'number') problems.push(`${f}: ${cat} #${i + 1} malformed`);
          else if (i && r[w - 1] > rows[i - 1][w - 1]) problems.push(`${f}: ${cat} #${i + 1} has more than #${i}`);
        });
      }
      return m;
    });
  const months = lists(['charts', 'deezer', 'spotify'], /^\d{4}-\d{2}\.json$/, 'month');
  // Weekly sites chart the weeks; library, year-end and all-time totals still come from the months
  const weeks = weekly ? lists(['weeks'], /^\d{4}-\d{2}-\d{2}\.json$/, 'week') : null;

  const replay = {};
  if (existsSync(at('replay'))) {
    for (const f of readdirSync(at('replay')).filter(f => /^\d{4}\.json$/.test(f))) {
      const r = read('replay/' + f);
      replay[f.slice(0, 4)] = { artists: r.artists || [], songs: r.songs || [], albums: r.albums || [] };
    }
  }
  const images = opt('images.json', []);
  const aliases = opt('aliases.json', {});
  const credits = opt('credits.json', {});
  const tracks = opt('tracks.json', {});
  const releases = opt('releases.json', {});
  const collectionListening = opt('collection-listening.json', {});
  const lengths = opt('lengths.json', {});
  for (const o of [tracks, lengths, aliases, credits, releases, collectionListening]) delete o._comment;

  const out = { builtAt: new Date().toISOString().slice(0, 10), months, ...(weekly ? { weeks } : {}), ...(views ? { views } : {}),
    replay, images, aliases, credits, tracks, releases, collectionListening, lengths };
  mkdirSync(join(ROOT, outDir), { recursive: true });
  writeFileSync(join(ROOT, outDir, 'data.js'),
    `// Generated by scripts/build.mjs from ${dataDir}/. Do not edit by hand.\nwindow.MUSICBOX = ` + JSON.stringify(out) + ';\n');

  problems.forEach(p => console.warn(`warning (${dataDir}):`, p));
  const ms = weekly ? weeks.map(w => w.week) : [...new Set(months.map(m => m.month))].sort();
  console.log(`${outDir}/data.js: ${ms.length} ${weekly ? 'weeks' : 'months'} (${ms[0]} to ${ms.at(-1)}) from ${(weekly ? weeks : months).length} files, ` +
    `${Object.keys(replay).length} Replay years, ${images.length} images`);
}

buildSite('data', 'site');

// Other people's sites: same page, shared code one folder up, their own data.js
const profiles = existsSync(join(ROOT, 'profiles'))
  ? readdirSync(join(ROOT, 'profiles')).filter(d => statSync(join(ROOT, 'profiles', d)).isDirectory()) : [];
const template = readFileSync(join(ROOT, 'site/index.html'), 'utf8');
const page = up => `<!-- Generated by scripts/build.mjs from site/index.html. Do not edit by hand. -->\n` +
  template.replace(/(href|src)="(styles\.css|favicon\.svg|charts\.js|app\.js)"/g, `$1="${up}$2"`);
for (const name of profiles) {
  const dir = 'profiles/' + name;
  if (!existsSync(join(ROOT, dir, 'weeks'))) {
    buildSite(dir, 'site/' + name);
    writeFileSync(join(ROOT, 'site', name, 'index.html'), page('../'));
    continue;
  }
  // Monthly and weekly charts side by side, with a switch between them
  const views = [{ label: 'Monthly', href: '../m/' }, { label: 'Weekly', href: '../w/' }];
  buildSite(dir, `site/${name}/m`, { views: views.map((v, i) => ({ ...v, current: i === 0 })) });
  buildSite(dir, `site/${name}/w`, { weekly: true, views: views.map((v, i) => ({ ...v, current: i === 1 })) });
  for (const sub of ['m', 'w']) writeFileSync(join(ROOT, 'site', name, sub, 'index.html'), page('../../'));
  writeFileSync(join(ROOT, 'site', name, 'index.html'), picker());
}

// The page at /<name>/ for someone with both monthly and weekly charts.
// Old links like /<name>/#/2024-05/songs still work: they're forwarded to the monthly charts.
function picker() {
  return `<!doctype html>
<!-- Generated by scripts/build.mjs. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>musicbox</title>
<script>if (location.hash.length > 2) location.replace('m/' + location.hash);</script>
<link rel="icon" type="image/svg+xml" href="../favicon.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../styles.css">
</head>
<body>
<header class="mast"><div class="in"><h1><a href="./">musicbox</a></h1></div></header>
<main class="wrap picker">
  <a class="pick" href="m/"><span class="eyebrow">Top 15 every month</span><b>Monthly charts</b><span class="hint">Month by month, with year-end charts, the library and awards.</span></a>
  <a class="pick" href="w/"><span class="eyebrow">Top 15 every week</span><b>Weekly charts</b><span class="hint">Friday to Thursday, like Billboard: faster moves and shorter runs.</span></a>
</main>
</body>
</html>
`;
}
